// this is variable one
let Number1

// this is variable two
let Number2

// this is my result
let result

// initialization
Number1=100
Number2=300

//initialize result
result=Number1 + Number2

console.log(result)

// calculate the product of two number in javascript

// this is variable 1
let number1

// this is variable 2
let number2

// initialization
number1=4;
number2=9;

// initialize result
result=number1*number2;

console.log(result)

// calculate the average marks of each students

let Eliza
let Rose
let Eli
let Abri
let Liz
let sum= Eli+Eliza+Liz+Abri+Rose

Eliza=60;
Eli=50;
Rose=65;
Abri=45;
Liz=70;

// initialize average
average=(Eliza+Eli+Rose+Abri+Liz)/5

console.log(result)

console.log(4 +5)
console.log("4 + 5")
console.log("4" +"5")
console.log('4' + '5')

// calculate the product of three numbers in javascript

var one = 8
var two = 2
var three = 3
var product = one * two * three
console.log("The product of the numbers is " + product)

// calculate the average marks of each students

var sum = one + two + three
console.log(" The sum of the three numbers is ", sum)

var average = sum/3

console.log("The average of the numbers is ", average)
